apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: playeconomy1384.azurecr.io/play.identity:latest
        env:
        - name: ServiceSettings__MessageBroker
          value: "SERVICEBUS"
        - name: MongoDbSettings__Host
          value: ""
        - name: MongoDbSettings__Port
          value: ""
        - name: MongoDbSettings__ConnectionString
          value: ""
        - name: RabbitMQSettings__Host
          value: ""
        - name: ServiceBusSettings__ConnectionString
          value: ""
        - name: IdentitySettings__AdminUserPassword
          value: ""
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5002
