microserviceName: "identity"

image:
  repository: playeconomy1384.azurecr.io/play.identity
  tag: 1.0.11

envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: /certificates/certificate.crt
  IdentitySettings__CertificateKeyFilePath: /certificates/certificate.key
  IdentityServerSettings__Clients__0__RedirectUris__0: https://playeconomy1384.northeurope.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: https://playeconomy1384.northeurope.cloudapp.azure.com/authentication/logout-callback

resources:
  limits:
    memory: "256Mi"
    cpu: "200m"

container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate:
  secretName: signing-cert
  hostName: playeconomy1384.northeurope.cloudapp.azure.com

serviceAccount:
  clientId: 3c52e950-4116-402a-a03f-2623e560d890