name: Play Identiy CICD

on:
  push:
    branches: ["master"]

jobs:
  generate-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Github Tag Bump
        id: tag_bump
        uses: anothrNick/github-tag-action@1.62.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_v: true
          INITIAL_VERSION: 1.0.38
          DEFAULT_BUMP: patch

    outputs:
      new_version: ${{steps.tag_bump.outputs.new_tag}}

  package-and-publish-contracts:
    runs-on: ubuntu-latest
    needs: generate-version
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore dependencies
        run: |
          dotnet restore src/Play.Identity.Contracts/ \
          --verbosity minimal

      - name: Pack
        run: |
          dotnet pack src/Play.Identity.Contracts/ \
          --configuration Release \
          -p:PackageVersion=${{needs.generate-version.outputs.new_version}} \
          -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/play.identity \
          -o out

      - name: Publish
        run: |
          dotnet nuget push out/*.nupkg
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
  build-and-publish-container:
    runs-on: ubuntu-latest
    needs: generate-version
    env:
      APP_NAME: playeconomy1384
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          client-id: ${{secrets._AZURE_CLIENT_ID}}
          tenant-id: ${{secrets._AZURE_TENANT_ID}}
          subscription-id: ${{secrets._AZURE_SUB_ID}}

      - name: ACR Login
        run: az acr login --name ${{env.APP_NAME}}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            playeconomy1384.azurecr.io/play.identity:${{needs.generate-version.outputs.new_version}}
          build-args: |
            GITHUB_PAT=${{secrets.GITHUB_TOKEN}}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group playeconomy1384 --name playeconomy1384

      - name: Install Helm
        uses: azure/setup-helm@v2.0

      - name: Login to Helm registry
        shell: pwsh
        run: |
          $helmUser="00000000-0000-0000-0000-000000000000"
          $helmPassword=az acr login --name ${{env.APP_NAME}} --expose-token --output tsv --query accessToken
          helm registry login "${{env.APP_NAME}}.azurecr.io" --username $helmUser --password $helmPassword

      - name: Deploy helm chart
        shell: pwsh
        run: |
          $registry="${{env.APP_NAME}}.azurecr.io"
          $namespace="identity"
          $serviceName="identity-service"
          $chartVersion="0.1.0"

          helm upgrade $serviceName oci://$registry/helm/microservice \
          --version "$chartVersion" \
          -f helm/values.yaml \
          -n $namespace \
          --set image.tag=${{needs.generate-version.outputs.new_version}}
          --install \
          --wait
